ENV=. $(BASEDIR)/venv/bin/activate && env LD_LIBRARY_PATH=$(BASEDIR)/venv/lib:$(BASEDIR)/venv/lib64/:${LD_LIBRARY_PATH}
PYTHON=$(ENV) python 
HOG_DIMENSIONS=243
SIFT_DIMENSIONS=132
MEANS=500
HOG_PERCENTAGE=0.02
SIFT_PERCENTAGE=1.00
FLANN_PRECISION=0.97
